language: php

php:
  - 7.1
  - 7.2
  - 7.3

before_script:
  - composer update


script: vendor/bin/phpunit -c phpunit.xml --coverage-text

notifications:
  email:
    recipients:
      - slps970093@gmail.com
    on_success: always
    on_failure: always