language: php



php:
  - 7.1
  - 7.2
  - 7.3

before_script:
  - composer update


script: vendor/bin/phpunit -c phpunit.xml --coverage-clover=clover.xml

notifications:
  email:
    recipients:
      - slps970093@gmail.com
    on_success: always
    on_failure: always

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 93cc1dcf-2f91-406f-a079-5b678e9581e6

